#!/bin/bash

sudo rm /usr/share/cowsay/cows/bud-frogs.cow
sudo rm /usr/share/cowsay/cows/bunny.cow
sudo rm /usr/share/cowsay/cows/calvin.cow
sudo rm /usr/share/cowsay/cows/cheese.cow
sudo rm /usr/share/cowsay/cows/cock.cow
sudo rm /usr/share/cowsay/cows/cower.cow
sudo rm /usr/share/cowsay/cows/daemon.cow
sudo rm /usr/share/cowsay/cows/dragon.cow
sudo rm /usr/share/cowsay/cows/dragon-and-cow.cow
sudo rm /usr/share/cowsay/cows/elephant-in-snake.cow
sudo rm /usr/share/cowsay/cows/eyes.cow
sudo rm /usr/share/cowsay/cows/flaming-sheep.cow
sudo rm /usr/share/cowsay/cows/ghostbusters.cow
sudo rm /usr/share/cowsay/cows/gnu.cow
sudo rm /usr/share/cowsay/cows/hellokitty.cow
sudo rm /usr/share/cowsay/cows/kangaroo.cow
sudo rm /usr/share/cowsay/cows/kiss.cow
sudo rm /usr/share/cowsay/cows/kosh.cow
sudo rm /usr/share/cowsay/cows/luke-koala.cow
sudo rm /usr/share/cowsay/cows/mech-and-cow.cow
sudo rm /usr/share/cowsay/cows/milk.cow
sudo rm /usr/share/cowsay/cows/moofasa.cow
sudo rm /usr/share/cowsay/cows/pony.cow
sudo rm /usr/share/cowsay/cows/pony-smaller.cow
sudo rm /usr/share/cowsay/cows/ren.cow
sudo rm /usr/share/cowsay/cows/skeleton.cow
sudo rm /usr/share/cowsay/cows/snowman.cow
sudo rm /usr/share/cowsay/cows/stegosaurus.cow
sudo rm /usr/share/cowsay/cows/stimpy.cow
sudo rm /usr/share/cowsay/cows/suse.cow
sudo rm /usr/share/cowsay/cows/three-eyes.cow
sudo rm /usr/share/cowsay/cows/turkey.cow
sudo rm /usr/share/cowsay/cows/turtle.cow
sudo rm /usr/share/cowsay/cows/unipony.cow
sudo rm /usr/share/cowsay/cows/unipony-smaller.cow
sudo rm /usr/share/cowsay/cows/vader.cow
sudo rm /usr/share/cowsay/cows/vader-koala.cow
sudo rm /usr/share/cowsay/cows/www.cow
